theme: jekyll-theme-cayman
title: International workshop on Performance modelling, Runtime System and Applications at the Exascale (EXA_PMRA20)
description: To be held in conjunction with ICPP2020 - The 49th International Conference on Parallel Processing
show_downloads: false
github:
  is_project_page: false
